name: Build and Push to ECR using Pack CLI

on:
  push:
    branches:
      - '*'

jobs:
  build_and_push:
    runs-on: self-hosted

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Pack CLI
      run: |
        PACK_CLI_VERSION="0.22.0"
        wget -q -O pack.tgz "https://github.com/buildpacks/pack/releases/download/v${PACK_CLI_VERSION}/pack-v${PACK_CLI_VERSION}-linux.tgz"
        sudo tar xvf pack.tgz -C /usr/local/bin --no-same-owner
        pack --version

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Authenticate on GCR
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Build and push Docker image
      run: |
        DOCKER_REPO=361265061473.dkr.ecr.us-east-1.amazonaws.com
        IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)

        make DOCKER_REPO=$DOCKER_REPO DOCKER_TAG=$IMAGE_TAG pack

        docker push $DOCKER_IMAGE:$IMAGE_TAG

    - name: Clean up Docker cache
      run: |
        docker system prune -af --volumes
        docker builder prune -af